services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
  web:
    build:
      context: .
      dockerfile: dockerfile.web
    ports:
      - "3000:2000"
    environment:
      REACT_APP_BACKEND_URL: http://localhost:3006
    depends_on:
      - server
      - db
    restart: unless-stopped
  server:
    build:
      context: .
      dockerfile: dockerfile.server
    ports:
      - "3006:3005"
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/mydb?schema=public
    depends_on:
      - db
